### PR TITLE
Create an sdk exception module and use it in the bmi model

### PR DESCRIPTION
**Pull request by hellkite500**
Move the `UnknownBMIVariable` custom exception into the sdk package and expose it to the package namespace for use with bmi models.

### CODE REVIEW

**Comment by hellkite500** [comment]
Note I branched this off #22 since it introduced the package `__init__.py` which is modified here.

**Review by aaraney — CHANGES_REQUESTED** [review]
I think you might just not have pushed up the code that uses the `UnknownBmiVariable` exception in the `Bmi_Model`, yeah?

**Comment by hellkite500** [comment]
> I think you might just not have pushed up the code that uses the `UnknownBmiVariable` exception in the `Bmi_Model`, yeah?

It was already using it in a couple of the functions, I just moved the exception class into the sdk package and imported it instead of using a local definition.

**Comment by aaraney** [comment]
Ah I see. I just looked at the diff.

**Review by aaraney — APPROVED** [review]

**Review by taddyb — APPROVED** [review]
LGTM!

**Pull request merged**
