### PR TITLE
ci: add black pre-commit hook

### PR DESCRIPTION
**Pull request by aaraney**
Add black code formatter as a `pre-commit` hook. Once, #22 and  #23 have merged, I will set this up in CI.

### CODE REVIEW

**Comment by taddyb** [comment]
I'm not sure we need this since we already have code linting coverage from Ruff: https://docs.astral.sh/ruff/

the tl;dr about Ruff is it is a code linter/formatter built in Rust that claims 10-100x speed increases over it's competition. Ruff is from the company astral which released `uv`, the Rust-based replacement for pip that you see in the `.github/workflows` to speed up environment builds

**Comment by aaraney** [comment]
@taddyb, you are absolutely correct! I am just showing my age! I was not aware of the `ruff` project. Looks super neat and i'm a big fan of `rust`. 

`ruff` / astral raise some interesting moral questions about OSS. I am not a huge fan of a company coming threw and porting / ripping off tons of projects that have been around for years that have existing communities and then making money off of it. Of course, the licensing of the projects they've ported are permissible, it just feels scummy. I think unfortunately as a result, a lot of the smaller projects that laid the ground work for what astral is developing will likely die over time and that is sad to see. For example, i've been using `black` for 5+ years. I am all for fast and efficient software and i'm really glad to see that we might finally have some unification of tools in the python ecosystem, but to use an idiom a rock climbing mentor frequently used, it doesn't give me the warm and fuzzies.

**Comment by hellkite500** [comment]
> porting / ripping off tons of projects that have been around for years

Isn't this also the premise of OSS? 😉

**Comment by taddyb** [comment]
If you look back at the origins for the term "linting," it's from a C utility called Lint which still exists today. Despite [wikipedia](https://en.wikipedia.org/wiki/Lint_(software)) claiming it's cross-platform, people use their linting software of choice which usually isn't Lint. Lint laid the foundation for Black, just as Black probably laid some of the foundation for Ruff!

**Comment by aaraney** [comment]
> Isn't this also the premise of OSS? 😉

It's all about that free labor, lol.

> If you look back at the origins for the term "linting," it's from a C utility called Lint which still exists today. Despite [wikipedia](https://en.wikipedia.org/wiki/Lint_(software)) claiming it's cross-platform, people use their linting software of choice which usually isn't Lint. Lint laid the foundation for Black, just as Black probably laid some of the foundation for Ruff!

Yeah, to me, it's not about the novelty of the idea per say, but that tools like `black` that astral have ported built trust and communities around those tools _without_ the presence of a company steering things. I think its pretty fair to say that if tools like `black` had a more pervasive license they would not have had the same level of success. So, the openness of their license plays some part in their success. Likewise, I think its safe to assume that the priorities of a company vs someone or group of people who work on OSS are very different. Redis is the latest great example of corporate greed ruining an OSS project.

All of this to say, I don't have an issue with porting or rewriting work to make it faster or do it slightly differently. I think diversity is great! However, I do have an issue when a company seemingly swoops in under the guise that _our tools are better because they are faster_ and ports existing community developed tools, aims to move users off of the tools they ported, and gives little credit or contribution along the way. It just feels gross and against the sprit of OSS.

Of course, you have to make a living and dev tools are a hot market with VCs chomping at the bit to fund projects in this space. It just gives off bad vibes IMO.

**Comment by hellkite500** [comment]
I haven't dug too far into astral as a company or their business model/practices.  I agree that it is worth watching out for signs of trouble, but at least for the things we are using on this project (ruff and ruff-format), they are similarly permissively licensed, and do carry attribution (at least in some form) to the lineage of projects they derived work from
https://github.com/astral-sh/ruff?tab=MIT-1-ov-file#readme

I would say that at face value, at least for ruff, the need/use was actually proved by the development community of large open source projects needing better tooling that that existing ones couldn't provide.  Don't know if you looked at this from a couple years ago (https://notes.crmarsh.com/python-tooling-could-be-much-much-faster) but it sets the stage for Astral as a company based on the early adoption/use of ruff even before it was really feature rich.  That definitely says something about the need for these kinds of tools, and the evolution of Python in general over the past decade or so.

**Pull request closed without merging**
